name: Semantic Release Dry Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Fetch main branch
        if: github.event_name == 'pull_request'
        run: git fetch origin main:main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Run semantic release dry-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running semantic release dry-run..."
          echo "Next version would be:"
          semantic-release version --print
          echo "---"
          echo "Last released version:"
          semantic-release version --print-last-released || echo "No previous releases found"
